### ISSUE TITLE
最新的版本，手动执行sh文件时，出现错误

### ISSUE THREAD

**Issue by rockhia** [Oscar1011/XarrNotifyScripts#3]
root@sonarr:/# sh "/XarrNotifyScripts/xarr_notify.sh"
Traceback (most recent call last):
  File "/XarrNotifyScripts/xarr_notify.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by rockhia** [comment]
映射路径下的文件有这几个。
![2022-03-01_17-40-03](https://user-images.githubusercontent.com/90016652/156144336-0567249a-b31b-4c77-b2c6-0b5fa65228aa.jpg)

**Comment by Oscar1011** [comment]
> 映射路径下的文件有这几个。 ![2022-03-01_17-40-03](https://user-images.githubusercontent.com/90016652/156144336-0567249a-b31b-4c77-b2c6-0b5fa65228aa.jpg)

安装一下依赖   pip3 install pyyaml
我的没有提示错误。我以为是自带的库

**Comment by rockhia** [comment]
已经可以推送了。请问radarr怎么配置呢？出现同样的问题，但是无法安装python3发自我的华为手机-------- 原始邮件 --------发件人： Oscar1011 ***@***.***>日期： 2022年3月1日周二 21:52收件人： Oscar1011/XarrNotifyScripts ***@***.***>抄送： rockhia ***@***.***>, Author ***@***.***>主    题： Re: [Oscar1011/XarrNotifyScripts] 最新的版本，手动执行sh文件时，出现错误 (Issue #3)



映射路径下的文件有这几个。 



安装一下依赖   pip3 install pyyaml

我的没有提示错误。我以为是自带的库

**Comment by rockhia** [comment]
已解决
