### ISSUE TITLE
请问Radarr怎么配置呢？

### ISSUE THREAD

**Issue by rockhia** [Oscar1011/XarrNotifyScripts#4]
参考sonarr的方式无法安装Python3
![IMG_20220301_221244](https://user-images.githubusercontent.com/90016652/156185394-990f53da-0375-4986-a432-144a085801f8.jpg)

**Comment by Oscar1011** [comment]
apt-get update 后再install尝试下

**Comment by rockhia** [comment]
建议教程直接傻瓜化操作。
docker exec -it sonarr /bin/bash
docker exec -it radarr /bin/bash

apt-get update
apt-get install python3
apt-get install python3-pip
pip3 install requests
pip3 install pyyaml
pip3 -V

sh "/XarrNotifyScripts/xarr_notify.sh"

**Comment by Oscar1011** [comment]
哈哈好的。等会儿更新进去
