### ISSUE TITLE
大佬帮忙看看

### ISSUE THREAD

**Issue by frankenston** [Oscar1011/XarrNotifyScripts#5]
sonarr添加connect的时候报错。Script exited with code: 255，加载的xarr_notify.sh这个脚本。
我在命令行手动运行报错
root@linuxserver-sonarr1:/# sh downloads/Moon\ Knight/xarr_notify.sh 
downloads/Moon Knight/xarr_notify.sh: 8: Syntax error: newline unexpected

**Comment by Oscar1011** [comment]
脚本放置的路径不要包含空格试试

**Comment by frankenston** [comment]
root@duobao:/volume2/xjj/downloads/ja# sh /volume2/xjj/downloads/ja/xarr_notify.sh 
/volume2/xjj/downloads/ja/xarr_notify.sh: line 7: syntax error near unexpected token `newline'
/volume2/xjj/downloads/ja/xarr_notify.sh: line 7: `<!DOCTYPE html>'
还是报错

**Comment by Oscar1011** [comment]
手动修改过xarr_notify.sh ？ 文件只有3行。报错在第7行

**Comment by frankenston** [comment]
文件我编辑看是这样的






<!DOCTYPE html>
这个html这个就是第七行，前面都是换行。
能加大佬个qq不，咨询下

**Comment by frankenston** [comment]
我的qq 118166498

**Comment by Oscar1011** [comment]
https://t.me/+6o1Wo7ktTR4yYWU1    建了个tg群

**Comment by Oscar1011** [comment]
文件下载问题
