### ISSUE TITLE
请问:能帮看看吗？

### ISSUE THREAD

**Issue by wlhwlh0482** [Oscar1011/XarrNotifyScripts#6]
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    0,
User gid:    0,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
2022-05-27 12:27:14.768 | ERROR    | Logger:error:17 - [主程序初始化异常]异常信息为:(<class 'IsADirectoryError'>, IsADirectoryError(21, 'Is a directory'), <traceback object at 0x7f14c9126580>),
Traceback (most recent call last):,
  File "/app/Config.py", line 7, in <module>,
    with open("config/Setting.yml", "r", encoding="utf-8") as f:,
IsADirectoryError: [Errno 21] Is a directory: 'config/Setting.yml',
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "Main.py", line 6, in <module>,
    import TMDB,
  File "/app/TMDB.py", line 6, in <module>,
    from Config import WXHOST_APIKEY, WXHOST, TMDB_KEY, TV_PREFER_LANGUAGE, TV_PREFER_GENRE_ID, MOVIES_PREFER_LANGUAGE, \,
  File "/app/Config.py", line 37, in <module>,
    from Pusher import push_to_enterprise_wechat,
  File "/app/Pusher.py", line 8, in <module>,
    from Config import CorpID, CorpSecret, TokenApi, PushTitle, AgentID, PushApi, Manager,
ImportError: cannot import name 'CorpID' from partially initialized module 'Config' (most likely due to a circular import) (/app/Config.py),
[cmd] python3 exited 1,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,

**Comment by wlhwlh0482** [comment]
谢谢！麻烦你了，dokcer版已搞好。

**Comment by Oscar1011** [comment]
确认下 配置文件是否存在  Setting.yml

**Comment by Oscar1011** [comment]
问题提错地方拉。这里不是docker版

**Comment by wlhwlh0482** [comment]
不好意思，配置文件放错目录了.已经解决，非常感谢.支付宝留言是我.不用回了.再次感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月27日(周五) 下午4:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Oscar1011/XarrNotifyScripts] 请问:能帮看看吗？ (Issue #6)




 
确认下 配置文件是否存在  Setting.yml
